#!/bin/bash
# Boot entry point for panda-bot. It wears two hats:
#
#   unsupervised (a human, `npm start`, a service unit) — make sure the
#     gitignored supervisor start.sh exists, then hand the process over to it.
#   supervised (PANDA_SUPERVISED=1, set by start.sh) — run the bot once and
#     hand node's exit code back up, so start.sh decides what happens next.
#
# Why the supervisor has to be a separate, gitignored file: it stays running
# across every restart, and bash reads a script incrementally as it executes —
# so a `git pull` that rewrote the file underneath it would corrupt the loop
# mid-run. start.sh is never touched by git; run.sh is only ever executing while
# node is, and the pull happens strictly between those.
cd "$(dirname "$0")" || exit 1

# Search needs a private SearXNG on loopback, and a fresh checkout has neither
# the container nor its (gitignored) settings.yml. Run before either branch so a
# crash-restart revives it too. Costs one health probe when it is already up,
# and never fails the boot — see scripts/ensure-searxng.sh.
[ -x scripts/ensure-searxng.sh ] && ./scripts/ensure-searxng.sh

if [ -n "$PANDA_SUPERVISED" ]; then
  node src/index.js
  exit $?
fi

# Bump this marker when the template below changes — a start.sh carrying an
# older marker is regenerated on the next unsupervised launch.
START_MARKER='# panda start.sh v1 — generated by run.sh, do not commit'

if [ ! -f start.sh ] || ! grep -qF "$START_MARKER" start.sh; then
  cat > start.sh <<'START_SH'
#!/bin/bash
# panda start.sh v1 — generated by run.sh, do not commit
#
# The supervisor. Pulls main, runs the bot, repeats:
#   exit 0  -> clean stop (SIGINT/SIGTERM), loop ends
#   exit 42 -> self_fix restart; the fix is already merged into main, so the
#              pull at the top of the loop is what actually loads it
#   other   -> crash; pull and restart after 3s
#
# This file is gitignored on purpose. Edit the template in run.sh instead — this
# copy is regenerated whenever run.sh's version marker changes.
cd "$(dirname "$0")" || exit 1
export PANDA_SUPERVISED=1

while :; do
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if ! git pull --ff-only origin main; then
      echo "[start.sh] git pull failed — booting the code already on disk"
    fi
  fi

  bash run.sh
  code=$?
  if [ "$code" -eq 0 ]; then
    echo "[start.sh] clean exit — stopping"
    break
  elif [ "$code" -eq 42 ]; then
    echo "[start.sh] self-fix restart — pulling and reloading"
  else
    echo "[start.sh] crashed (exit $code) — restarting in 3s"
    sleep 3
  fi
done
START_SH
  chmod +x start.sh
fi

if [ ! -x start.sh ]; then
  echo "[run.sh] could not create start.sh — booting once, without the pull-and-restart loop" >&2
  exec node src/index.js
fi

exec ./start.sh
